### ISSUE TITLE
bug in example rating-dropdown "Show more.." button handler.

### ISSUE THREAD

**Issue by dublx** [contentful/widget-sdk#112]
It looks like the rating-dropdown button "Show entries with the same rating" doesnt work.
In https://github.com/contentful/widget-sdk/blob/master/examples/rating-dropdown/app.html#L105 (commit 1da18cd) it should check `.length` of the `entries.items` property, not on `entries` directly.

##### Fix
```js
...
          if (entries.items.length) {
            var content = entries.items.map(renderEntry)
...
```
I tested this change and it worked for me.

**Comment by geigerzaehler** [comment]
Hey @dublx! Thanks for reporting this. Do you feel like contributing a PR :wink:?
