### ISSUE TITLE
Inconsistent validation between API and UI

### ISSUE THREAD

**Issue by floelhoeffel** [contentful/widget-sdk#86]
When uploading a widget through the API, IDs with a "-" are accepted. However once the widget gets assigned to a ContentType, saving in UI fails with a validation error not allowing a "-" in the filename.

API response when saving CT:

{
 "sys": {
   "type": "Error",
   "id": "ValidationFailed"
 },
 "message": "Validation error",
 "details": {
   "errors": [
     {
       "name": "regexp",
       "details": "Does not match /^[a-zA-Z][a-zA-Z0-9_]*$/",
       "path": [
         "controls",
         2,
         "widgetId"
       ],
       "value": "foo-widget",
       "pattern": "^[a-zA-Z][a-zA-Z0-9_]*$"
     }
   ]
 },
 "requestId": "content-api:6GCmiNIqDCuUqkC2w8oy4K"
}

**Comment by geigerzaehler** [comment]
Has been fixed in the API
